services:
  proxy:
    container_name: nginx
    image: nginx:1.13-alpine
    ports:
      - 80:80
    restart: always
    volumes:
    - ./proxy/conf:/etc/nginx/conf.d/default.conf:ro
    depends_on: 
      - web
  
  web:
    build: app
    user: root
    expose: 
    - 80
    volumes:
      - ./app:/var/www/html/

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    expose:
    - 80
  
  
