version: '3.8'

services:
  bamboo-server:
    container_name: bamboo-server
    image: atlassian/bamboo
    volumes:
    - bambooVolume:/var/atlassian/application-data/bamboo
    ports:
    - 8085:8085
    - 54663:54663
  
  bamboo-agent:
    container_name: bamboo-agent
    image: atlassian/bamboo-agent-base
    environment:
    - BAMBOO_SERVER=bamboo-server
    - bambooVolume:/var/atlassian/application-data/bamboo

volumes:
  bambooVolume: