version: '3.8'

services:
  bamboo-server:
    container_name: bamboo-server
    image: atlassian/bamboo
    volumes:
    - bambooVolume:/var/atlassian/application-data/bamboo
    ports:
    - 8085:8085
    - 54663:54663
    environment:
    - TZ=Europe/Paris
    - ATL_JDBC_URL=jdbc:postgresql://postgres:5432/bamboo
    - ATL_JDBC_USER=postgres
    - ATL_JDBC_PASSWORD=bamboo
    - ATL_DB_TYPE=postgresql
    depends_on:
    - postgres
  
  bamboo-agent:
    container_name: bamboo-agent
    image: atlassian/bamboo-agent-base
    environment:
    - TZ=Europe/Paris
    - BAMBOO_SERVER=http://52.56.238.221:8085/agentServer/
    - bambooAgentVolume:/var/atlassian/application-data/bamboo-agent
    depends_on:
    - bamboo-server

  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
    - db-data:/var/lib/postgresql/data
    environment:
    - TZ=Europe/Paris
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=bamboo
    - POSTGRES_DB=bamboo
    ports:
      - "5432:5432"
    restart: always

volumes:
  bambooVolume:
  bambooAgentVolume:
  db-data: