version: '3.8'

services:
  bamboo-server:
    container_name: bamboo-server
    image: atlassian/bamboo:8.1.1
    volumes:
    - bambooVolume:/var/atlassian/application-data/bamboo
    ports:
    - 8085:8085
    - 54663:54663
    environment:
    - TZ=Europe/Paris
    - SECURITY_TOKEN=5UBZHCQk2HLzJnQZib0C
    - ATL_BAMBOO_DISABLE_AGENT_AUTH=false
    - ATL_BASE_URL=http://18.132.202.23:8085
    - ATL_JDBC_URL=jdbc:postgresql://postgres:5432/bamboo
    - ATL_JDBC_USER=postgres
    - ATL_JDBC_PASSWORD=bamboo
    - ATL_DB_TYPE=postgresql
    - ATL_ADMIN_USERNAME=admin12345
    - ATL_ADMIN_PASSWORD=admin@Bamboo
    - ATL_ADMIN_FULLNAME=Admin
    - ATL_ADMIN_EMAIL=admin@localhost.com
    depends_on:
    - postgres
  
  # bamboo-agent:
  #   container_name: bamboo-agent
  #   image: atlassian/bamboo-agent-base:8.1.1
  #   environment:
  #   - TZ=Europe/Paris
  #   - SECURITY_TOKEN=5UBZHCQk2HLzJnQZib0C
  #   - BAMBOO_SERVER=http://bamboo-server:8085/agentServer/
  #   - bambooAgentVolume:/var/atlassian/application-data/bamboo-agent
  #   depends_on:
  #   - bamboo-server

  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
    - db-data:/var/lib/postgresql/data
    environment:
    - TZ=Europe/Paris
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=bamboo
    - POSTGRES_DB=bamboo
    ports:
      - "5432:5432"
    restart: always

volumes:
  bambooVolume:
  bambooAgentVolume:
  db-data: