version: '3.8'

services:
  bamboo-server:
    container_name: bamboo-server
    image: atlassian/bamboo:8.1.1
    volumes:
    - bambooVolume:/var/atlassian/application-data/bamboo
    ports:
    - 8085:8085
    expose:
    - 54663
    environment:
    - TZ=Europe/Paris
    - SECURITY_TOKEN=5UBZHCQk2HLzJnQZib0C
    - ATL_BAMBOO_DISABLE_AGENT_AUTH=false
    - ATL_JDBC_URL=jdbc:postgresql://postgres:5432/bamboo
    - ATL_JDBC_USER=postgres
    - ATL_JDBC_PASSWORD=bamboo
    - ATL_DB_TYPE=postgresql
    - ATL_ADMIN_USERNAME=admin12345
    - ATL_ADMIN_PASSWORD=admin@Bamboo
    - ATL_ADMIN_FULLNAME=Admin
    - ATL_ADMIN_EMAIL=admin@localhost.com
    depends_on:
    - postgres
  
  bamboo-agent:
    container_name: bamboo-agent
    image: atlassian/bamboo-agent-base:8.1.1
    environment:
    - TZ=Europe/Paris
    - SECURITY_TOKEN=5UBZHCQk2HLzJnQZib0C
    - BAMBOO_SERVER=http://bamboo-server:8085/agentServer/
    - bambooAgentVolume:/var/atlassian/application-data/bamboo-agent
    depends_on:
    - bamboo-server

  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
    - db-data:/var/lib/postgresql/data
    environment:
    - TZ=Europe/Paris
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=bamboo
    - POSTGRES_DB=bamboo
    expose:
    - 5432
    restart: always

  xld:
    container_name: xld
    image: xebialabs/xl-deploy:10.3
    ports:
    - 8080:4516
    volumes:
    - xldVolume:/opt/xebialabs/xl-deploy-server
    environment:
    - ACCEPT_EULA=Y
    - ADMIN_PASSWORD=xebialabs

  xlr:
    container_name: xlr
    image: xebialabs/xl-release:10.3
    ports:
    - 8081:5516
    volumes:
    - xlrVolume:/opt/xebialabs/xl-release-server
    environment:
    - ACCEPT_EULA=Y
    - ADMIN_PASSWORD=xebialabs

  mailhog:
    container_name: mailserver
    image: mailhog/mailhog:v1.0.1
    ports:
    - 8025:8025

volumes:
  bambooVolume:
  bambooAgentVolume:
  xldVolume:
  xlrVolume:
  db-data:
