services:
  proxy:
    container_name: nginx
    build: proxy
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
    - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./proxy/default.conf:/etc/nginx/conf.d/default.conf:ro
    - ./certbot/www/:/var/www/certbot/:ro
    #- ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on: 
      - web
  
  web:
    build: app
    user: root
    expose: 
    - 80
    volumes:
      - ./app:/var/www/html/

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    expose:
    - 80
  
  certbot:
    image: certbot/certbot:latest
    volumes:
    - ./certbot/www/:/var/www/certbot/:rw
    - ./certbot/conf/:/etc/letsencrypt/:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    #entrypoint: certbot certonly --webroot -w /var/www/certbot --staging --register-unsafely-without-email -d app-3-250-133-100.nip.io --agree-tos --force-renewal
      
