services:
  web:
    build: app
    user: root
    ports: 
      - '80:80'
      - '443:443'
    volumes:
      - ./app:/var/www/html/
      #- ./http.conf:/etc/apache2/sites-available/000-default.conf
      #- ./https.conf:/etc/apache2/sites-available/default-ssl.conf
      #- ./certbot/www/:/var/www/certbot/:ro
      #- ./certbot/conf/:/etc/ssl/:ro
  # certbot:
  #   image: certbot/certbot:latest
  #   volumes:
  #   - ./certbot/www/:/var/www/certbot/:rw
  #   - ./certbot/conf/:/etc/letsencrypt/:rw
      
